name: whatsapp_clone
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  avatars: ^3.0.2
  flutter_advanced_avatar: ^1.1.0
  story_viewer: ^0.2.0
  get: ^4.6.5
  image_picker: ^0.8.5+3
  flutter_screenutil: ^5.5.4
  firebase_core: ^1.21.1
  firebase_auth: ^3.7.0
  cloud_firestore: ^3.4.6
  firebase_storage: ^10.3.7
  riverpod: ^1.0.3
  country_picker: ^2.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.10.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
flutter:
  uses-material-design: true
  assets:
    - assets/
